// Isi file data-toko.js
const listToko = [
    // Tempel (Paste) hasil dari Excel di sini
    { kode: "TIX8", nama: "RAYA PULO AMPEL" },
{ kode: "TRIS", nama: "RUKO RAKATA ASRI" },
{ kode: "TKJB", nama: "RAYA BOJEN" },
{ kode: "TTJE", nama: "PESANGGRAHAN WALANTAKA" },
{ kode: "T7QX", nama: "MENES 20A" },
{ kode: "TCEH", nama: "TELUK LADA SOBANG" },
{ kode: "TBQF", nama: "CIGEULIS PANDEGLANG" },
{ kode: "FKHM", nama: "PERSADA BANTEN" },
{ kode: "FTNQ", nama: "CITOREK" },
{ kode: "T6CD", nama: "PELAMUNAN KRAMATWATU" },
{ kode: "F7FS", nama: "CIPANAS LEBAK" },
{ kode: "T96C", nama: "CURUG SERANG" },
{ kode: "TFJT", nama: "KORONCONG" },
{ kode: "TCL9", nama: "SUDAMANIK LEBAK" },
{ kode: "TJNT", nama: "SYECH NAWAWI 2" },
{ kode: "TB7O", nama: "KALIGANDU CILEGON NO.82" },
{ kode: "TZJH", nama: "RAYA MUNCANG CIMINYAK" },
{ kode: "TKD8", nama: "KALORAN SERANG" },
{ kode: "THGZ", nama: "PULORIDA" },
{ kode: "FOSH", nama: "RAYA PICUNG MUNJUL KM. 03" },
{ kode: "FVSB", nama: "SPBU CISALAM" },
{ kode: "T0A8", nama: "RAYA SALIRA PULOAMPEL 23" },
{ kode: "F9JU", nama: "CISAAT PALKA KM 25" },
{ kode: "TTH7", nama: "RAYA SERANG KM 65" },
{ kode: "TMMT", nama: "CENING" },
{ kode: "FK1N", nama: "TERATAI" },
{ kode: "TBBD", nama: "CARINGIN" },
{ kode: "TKBV", nama: "FRESH DC LEBAK" },
{ kode: "TAVZ", nama: "PANIMBANG SIDAMUKTI" },
{ kode: "TSBG", nama: "MAJASARI SOBANG" },
{ kode: "TY96", nama: "SIPAYUNG" },
{ kode: "FU0K", nama: "PURI MAS" },
{ kode: "TUDI", nama: "GRAND SUKAWANA" },
{ kode: "FZ9R", nama: "CIBALIUNG 2" },
{ kode: "TZWV", nama: "RAYA PETIR" },
{ kode: "TSQ2", nama: "GUNUNG SARI" },
{ kode: "TES4", nama: "POINT PORT MERAK GF04" },
{ kode: "TVCU", nama: "BARUGBUG" },
{ kode: "TACW", nama: "PANGGUNG RAWI " },
{ kode: "F2B1", nama: "SAKETI 2" },
{ kode: "TYQ0", nama: "RAYA CIOMAS" },
{ kode: "F8CH", nama: "MUTIARA MAJA" },
{ kode: "TRAE", nama: "CIPUTRI" },
{ kode: "FEZK", nama: "CIPALABUH LEBAK" },
{ kode: "TA1T", nama: "POINT TERMINTAL PAKUPATAN" },
{ kode: "TN4W", nama: "TAMAN JAYA UJUNG KULON" },
{ kode: "TTOI", nama: "RAYA NAMBO CIRUAS" },
{ kode: "TIH5", nama: "RAYA LABUAN BATUBANTAR" },
{ kode: "TWFI", nama: "YUSUF MARTADILAGA SERANG" },
{ kode: "TMAW", nama: "CIKANDE PERMAI BLOK R" },
{ kode: "TWED", nama: "TAMBANG AYAM ANYER" },
{ kode: "FYBL", nama: "RAYA LABUAN KM 4" },
{ kode: "TBWA", nama: "CITRA MAJA BOULEVARD A01" },
{ kode: "T0HX", nama: "RAYA CIPANAS KM. 9" },
{ kode: "FE0T", nama: "RUKO MUTIARA SAPHIRE" },
{ kode: "TCNF", nama: "FRESH SA TIRTAYASA CILEGON" },
{ kode: "TZJ9", nama: "CITELUK CIKADU" },
{ kode: "FSSW", nama: "RAYA PERDANA" },
{ kode: "TKV7", nama: "RAYA PANIMBANG TJ. LESUNG" },
{ kode: "TIWG", nama: "ARGA RAYA CILEGON" },
{ kode: "T21M", nama: "PETIR" },
{ kode: "F68G", nama: "KORANJI PANDEGLANG" },
{ kode: "T1Q5", nama: "RAYA KRAGILAN" },
{ kode: "T8UF", nama: "MULTATULI RANGKAS" },
{ kode: "F0K7", nama: "PERUM ROYAL GARDEN" },
{ kode: "FQOR", nama: "AKSES POLDA 123" },
{ kode: "TLI7", nama: "KAMPUNG NAMBO" },
{ kode: "FXF6", nama: "SINDANG HEULA" },
{ kode: "F7P1", nama: "BRIGHT BY INDOMARET GROGOL" },
{ kode: "F0QY", nama: "CIAGEL KIBIN" },
{ kode: "F6M6", nama: "GRAND SUTRA SERANG" },
{ kode: "FRS9", nama: "RUKO SEION BLOK K2 NO 7 - 8" },
{ kode: "F8E2", nama: "RANGKAS NARIMBANG MULIA" },
{ kode: "TPEJ", nama: "CIMUNCANG SERANG" },
{ kode: "TTWF", nama: "RAYA ANYER SIRIH" },
{ kode: "T8SA", nama: "RAYA SERANG JAKARTA KM 7" },
{ kode: "FXVP", nama: "BAYAH CIKOTOK KM 8" },
{ kode: "TG5K", nama: "RAYA MAJA PAPANGGO" },
{ kode: "TKJ2", nama: "RUKO TAMAN CIRUAS" },
{ kode: "TPM0", nama: "MARGASARI PULO AMPEL" },
{ kode: "F3KO", nama: "MAJA CIBIUK" },
{ kode: "F6PS", nama: "RAYA MAJA CIBIUK" },
{ kode: "T19D", nama: "BHAYANGKARA SERANG" },
{ kode: "TMWK", nama: "PERUM PERMATA BANJAR ASRI" },
{ kode: "T7AV", nama: "CIPACUNG MAJASARI" },
{ kode: "T2LX", nama: "RAYA ANYER BANDULU" },
{ kode: "T4HY", nama: "SENOPATI ESTATE CIUJUNG" },
{ kode: "TG5O", nama: "GRAND SUTERA KRAGILAN" },
{ kode: "TPOQ", nama: "KP SADANG KIBIN" },
{ kode: "TYX0", nama: "PCI BLOK B9 NO 9" },
{ kode: "TMVQ", nama: "PERMATA SAFIRA REGENCY BLOK A1" },
{ kode: "TY33", nama: "RAYA PANDEGLANG SARUNI" },
{ kode: "TE2I", nama: "ALUN ALUN MALINGPING" },
{ kode: "FC8L", nama: "CITRALAND PURI SERANG" },
{ kode: "FHV8", nama: "PERUMAHAN WIDYA RESIDENCE" },
{ kode: "FXXV", nama: "SPBU BRIGHT BY INDOMARET IKPRI" },
{ kode: "TDFN", nama: "CISATA PANDEGLANG" },
{ kode: "FQT4", nama: "KIARA GARDEN 2" },
{ kode: "T83I", nama: "PONDOK TAKTAKAN INDAH" },
{ kode: "TIK8", nama: "TAMAN KRAKATAU RB NO. 36-37 " },
{ kode: "TOA5", nama: "TEGAL CABE" },
{ kode: "TVYK", nama: "ASRAMA POLISI LEBAK" },
{ kode: "FG8H", nama: "NAMBO ILIR" },
{ kode: "FKP5", nama: "BUKIT PALEM" },
{ kode: "T0UK", nama: "PONTANG- TPAA" },
{ kode: "T2UB", nama: "LINGKAR SELATAN KM 0.5" },
{ kode: "FLEO", nama: "PAGELARAN" },
{ kode: "TQ6X", nama: "RAYA MAJA JASINGA KM 01" },
{ kode: "T4IB", nama: "TEMBONG JAYA" },
{ kode: "TSGE", nama: "RAYA EMPAT LIMA SERANG" },
{ kode: "T0P6", nama: "BUKIT CILEGON ASRI 3-4" },
{ kode: "TEIR", nama: "PASAR DUKUH" },
{ kode: "FMPG", nama: "CENDRAWASIH SERANG" },
{ kode: "FNMH", nama: "BAROS SIMPANG" },
{ kode: "F0CD", nama: "RAYA LINGKAR CIWANDAN" },
{ kode: "TP84", nama: "WARUNG GUNUNG" },
{ kode: "F53Y", nama: "PERINTIS LABUAN" },
{ kode: "TJP6", nama: "SUNAN AMPEL CITANGKIL" },
{ kode: "TNHX", nama: "KESAWON SERANG" },
{ kode: "TAMS", nama: "SERANG PANDEGLANG KM 3.5" },
{ kode: "FL74", nama: "PURI CITRA" },
{ kode: "TBUK", nama: "KADUHEJO BOJONG" },
{ kode: "TTGD", nama: "LEBAK GEDONG" },
{ kode: "T3CV", nama: "PARK VILLE CITRA MAJA" },
{ kode: "TNS5", nama: "JONGJING KRAGILAN" },
{ kode: "FGPK", nama: "PURI KENCANA" },
{ kode: "TOCY", nama: "LEMBANG RAYA" },
{ kode: "TQ0L", nama: "PASAR PICUNG" },
{ kode: "TNCV", nama: "PONDOK CILEGON INDAH" },
{ kode: "TIAJ", nama: "JENDRAL SUDIRMAN SERANG" },
{ kode: "TGWS", nama: "KIARA SERANG" },
{ kode: "FASZ", nama: "PASAR CISIIH" },
{ kode: "TYLU", nama: "KEPUREN RESIDENCE" },
{ kode: "FEBE", nama: "CIPUTRI INDAH" },
{ kode: "T19E", nama: "RAYA CILEGON" },
{ kode: "TUBI", nama: "RANCA TALES" },
{ kode: "F8L8", nama: "SPBU KALODRAN" },
{ kode: "THC9", nama: "CIGADUNG PANDEGLANG" },
{ kode: "T5O6", nama: "POINT STASIUN SERANG" },
{ kode: "FI9D", nama: "PASAR SOBANG" },
{ kode: "T67N", nama: "RAYA DI PANJAITAN KM 2" },
{ kode: "TPZZ", nama: "WARUNG BANTEN" },
{ kode: "THUT", nama: "PARK LANE CITRA MAJA" },
{ kode: "TKMH", nama: "RAYA PAGELARAN" },
{ kode: "TKB0", nama: "DAHU CIKEUSAL" },
{ kode: "T42E", nama: "SILIWANGI  LEBAK" },
{ kode: "TLWZ", nama: "RAYA PANDEGLANG KM 1" },
{ kode: "FP7U", nama: "JUNTI ASRI" },
{ kode: "TT9X", nama: "SUMUR KOPO LABUAN" },
{ kode: "T74E", nama: "MANCAK" },
{ kode: "TCAE", nama: "RANCASENENG CIKEUSIK" },
{ kode: "T6M0", nama: "CILELES LEBAK BANTEN" },
{ kode: "T6ED", nama: "ANYAR SERANG" },
{ kode: "FBO0", nama: "JALUPANG" },
{ kode: "FDXU", nama: "NIKOMAS" },
{ kode: "T86N", nama: "WIDYA ASRI" },
{ kode: "TTXR", nama: "BUMI CIKANDE INDAH" },
{ kode: "TDZJ", nama: "IR SUTAMI CILEGON" },
{ kode: "T9B3", nama: "RAYA BANTEN" },
{ kode: "TQBE", nama: "CIBOLEGER" },
{ kode: "TLDG", nama: "RAYA JAMAKSARI" },
{ kode: "T3B5", nama: "RAYA TAKTAKAN CILOWONG" },
{ kode: "T5XA", nama: "YOS SUDARSO 22" },
{ kode: "T8VR", nama: "CIWANDAN 2" },
{ kode: "TV37", nama: "PENANCANGAN SERANG" },
{ kode: "TO7I", nama: "RAYA PANDEGLANG SERANG" },
{ kode: "FQ1F", nama: "GAJRUG" },
{ kode: "TVWS", nama: "PUSRI KEMANG" },
{ kode: "T1PM", nama: "SUNAN KALIJAGA 2" },
{ kode: "T6QN", nama: "RAYA SYEKHNAWAWI ALBANTANI" },
{ kode: "T404", nama: "SITURAGEN LEBAK" },
{ kode: "FMGK", nama: "LANGLANG BUANA RANGKAS" },
{ kode: "TLFJ", nama: "CIKULUR" },
{ kode: "TOLY", nama: "MEKAR AGUNG LEBAK" },
{ kode: "TQA7", nama: "CIBEDIL LEBAK" },
{ kode: "F124", nama: "BOJONEGORO" },
{ kode: "TJUE", nama: "DIPONEGORO" },
{ kode: "TN23", nama: "MERAK - 2" },
{ kode: "FSMU", nama: "TAMAN GRAHA ASRI" },
{ kode: "TF5R", nama: "JENDRAL SUDIRMAN LEBAK" },
{ kode: "T6XT", nama: "PAJAGAN LEBAK" },
{ kode: "TPWC", nama: "RAYA LETNAN JIDUN" },
{ kode: "FM19", nama: "CIGEULIS 2" },
{ kode: "FF4K", nama: "BAYAH CIKOTOK KM 2" },
{ kode: "TC7E", nama: "BAROS II" },
{ kode: "TIGT", nama: "RAYA PONTANG" },
{ kode: "TBW7", nama: "KARANG ASEM CIBEBER" },
{ kode: "TI92", nama: "SIMPANG TIGA" },
{ kode: "T86M", nama: "CISAIT KRAGILAN" },
{ kode: "FO1K", nama: "CIPANAS KM 17" },
{ kode: "FGHY", nama: "KRAGILAN GRIYA SENTOSA" },
{ kode: "TY2P", nama: "RAYA CARENANG" },
{ kode: "T4SY", nama: "TEMU PUTIH BLOK C" },
{ kode: "TQC6", nama: "WANASALAM LEBAK" },
{ kode: "THXK", nama: "SAKETI MALINGPING KM 17" },
{ kode: "T25I", nama: "PABRIK PANDEGLANG" },
{ kode: "TW9S", nama: "JOMBANG" },
{ kode: "T1EC", nama: "GEREM II" },
{ kode: "TY29", nama: "BAROS SUKACAI" },
{ kode: "T90Y", nama: "GEDONG DALEM" },
{ kode: "TOOC", nama: "CIMAMPANG LEBAK" },
{ kode: "TS7R", nama: "TAMAN BANTEN LESTARI 2" },
{ kode: "F150", nama: "PONDOK CILEGON INDAH" },
{ kode: "FCD3", nama: "RUKO GRAND CILEGON" },
{ kode: "T0LW", nama: "RAYA SENTUL NYAPAH" },
{ kode: "TCYU", nama: "PURI ANGGREK 2" },
{ kode: "TNEU", nama: "BUNDARAN PCI" },
{ kode: "TPVS", nama: "KYAI HAJI SOKHARI 37" },
{ kode: "TRR7", nama: "TAMAN CIRUAS" },
{ kode: "TZC8", nama: "RAYA BOJONEGARA KM 1" },
{ kode: "F3GG", nama: "RAYA LABUAN KM 02" },
{ kode: "TPF2", nama: "RAYA KADUBERA" },
{ kode: "FSGL", nama: "KP. CIKEUSIK" },
{ kode: "FZ4Y", nama: "SUNAN AMPEL 7" },
{ kode: "TP2G", nama: "BUMI AGUNG 2" },
{ kode: "TT3R", nama: "RAJAWALI CIBEBER " },
{ kode: "TPSN", nama: "RAYA ABDUL LATIF" },
{ kode: "TDB3", nama: "CIKEUSIK BINUANGEUN KM. 1" },
{ kode: "TI9Q", nama: "CIBALIUNG PADASUKA " },
{ kode: "TP1E", nama: "GORDA SERANG " },
{ kode: "F8RT", nama: "PULO AMPEL ARGAWANA" },
{ kode: "TY8Q", nama: "MUARA LEBAK" },
{ kode: "TV2Y", nama: "NYOMPOK SERANG" },
{ kode: "TOML", nama: "SAJIRA LEBAK" },
{ kode: "TJD0", nama: "CIUJUNG" },
{ kode: "TIKX", nama: "KITAPA SERANG" },
{ kode: "T36E", nama: "GEREM CILEGON" },
{ kode: "T1NO", nama: "CEMPAKA LEBAK" },
{ kode: "T61A", nama: "RAYA SYEKH NAWAWI KM.5" },
{ kode: "TEIC", nama: "SUKABARES WARINGIN KURUNG" },
{ kode: "TKX7", nama: "RAYA MALINGPING CIJAKU" },
{ kode: "TOGL", nama: "RAYA MAJA KOPO KM.1" },
{ kode: "FA72", nama: "GRAHA WALANTAKA" },
{ kode: "T86W", nama: "KRAMAT WATU 2" },
{ kode: "TUKG", nama: "BOJONG ANYER" },
{ kode: "TEB7", nama: "FRESH TOL SERANG TIMUR" },
{ kode: "T4PH", nama: "RAYA CIPTAYASA KM 12" },
{ kode: "FMIM", nama: "CIRUAS RINJANI" },
{ kode: "TIF6", nama: "ARGA BAJAPURA" },
{ kode: "FDJI", nama: "CIPEUCANG" },
{ kode: "TIG9", nama: "RAYA BANTEN KEBAHARAN" },
{ kode: "TLET", nama: "A.YANI CILEGON 5 - 6" },
{ kode: "TOUA", nama: "SUKADIRI KASUNYATAN" },
{ kode: "TGOW", nama: "FATAH HASAN" },
{ kode: "TPXI", nama: "PABUARAN UNYUR" },
{ kode: "TPCT", nama: "PARAKAN" },
{ kode: "TP8C", nama: "LOPANG INDAH" },
{ kode: "F597", nama: "TAMAN CIRUAS" },
{ kode: "FGML", nama: "GRIYA PERMATA ASRI SERANG" },
{ kode: "T40I", nama: "TIRTAYASA SERANG" },
{ kode: "TBGR", nama: "PIRANHA CILEGON" },
{ kode: "TK1C", nama: "SERANG HIJAU" },
{ kode: "TU8F", nama: "RAYA CILEGON BOJONEGARA" },
{ kode: "T1Y1", nama: "TAKTAKAN 3" },
{ kode: "TE3B", nama: "AHMAD YANI PANDEGLANG" },
{ kode: "T18Q", nama: "JOMBANG MESJID" },
{ kode: "TV5B", nama: "BUMI CIRUAS PERMAI 2" },
{ kode: "TCBJ", nama: "RAYA PANDEGLANG" },
{ kode: "F392", nama: "KRAMAT WATU" },
{ kode: "TL83", nama: "S.A. TIRTAYASA 48" },
{ kode: "TZEX", nama: "PURI KRAKATAU HIJAU NO 1" },
{ kode: "TAVE", nama: "SUKAMANAH LEBAK" },
{ kode: "TCGY", nama: "LEBAK PICUNG RANGKAS" },
{ kode: "TV3M", nama: "RAYA JENDRAL SUDIRMAN" },
{ kode: "TFWM", nama: "RAHONG MALINGPING" },
{ kode: "TGDA", nama: "PUSPA REGENCY" },
{ kode: "TPRH", nama: "MALINGPING CIJAKU KM 2" },
{ kode: "TGWZ", nama: "KRANGGOT CILEGON" },
{ kode: "TCUD", nama: "CIKONENG ANYER" },
{ kode: "FJY8", nama: "RAYA RANGKASBITUNG KM 14" },
{ kode: "TNM0", nama: "WARUNG JAUD" },
{ kode: "TUZR", nama: "JAKARTA SERANG KM 4" },
{ kode: "F1GY", nama: "PERTIGAAN CIPARAY" },
{ kode: "TFT1", nama: "KARANG SERANG" },
{ kode: "TX0T", nama: "KAREO JAWILAN" },
{ kode: "TD1I", nama: "RAYA CIPANAS KM 19" },
{ kode: "TVBG", nama: "SEPANG MOUNTAIN RESIDENCE 2" },
{ kode: "TY3K", nama: "PERUM CIKANDE PERMAI2" },
{ kode: "F68U", nama: "KRAKATAU" },
{ kode: "FXGX", nama: "PANTAI ANYER" },
{ kode: "T2ET", nama: "IR SOETAMI RANGKAS" },
{ kode: "TY5K", nama: "BUKIT BAJA CILEGON" },
{ kode: "T42A", nama: "KAPTEN TENDEAN KM 2" },
{ kode: "T8VN", nama: "MEKARSARI MERAK" },
{ kode: "TEZX", nama: "GUNUNG BATU KM 27" },
{ kode: "F554", nama: "CIKANDE 2" },
{ kode: "TUNJ", nama: "SASTRADIKARTA JOMBANG" },
{ kode: "TWII", nama: "RAYA SERANG SUKAMANAH" },
{ kode: "TYK4", nama: "SAWARNA" },
{ kode: "TC3J", nama: "SERDANG METROPOLIS" },
{ kode: "TJAN", nama: "RAYA SELIKUR KM 3.7" },
{ kode: "TSUH", nama: "RAYA PABUARAN" },
{ kode: "TPC7", nama: "D.I. PANJAITAN 2" },
{ kode: "T28E", nama: "BOJONEGORO III" },
{ kode: "TJM4", nama: "KRAMAT WATU 3" },
{ kode: "T1I8", nama: "PERMATA BANJAR ASRI" },
{ kode: "FHO6", nama: "KARANG TANJUNG" },
{ kode: "FLWP", nama: "MENES 2" },
{ kode: "FVO0", nama: "GRAND PESONA CILEGON" },
{ kode: "FZ29", nama: "AL AZHAR SERANG" },
{ kode: "TEQ9", nama: "SASTRADIKARTA" },
{ kode: "TLUI", nama: "RAYA BAGENDUNG" },
{ kode: "TM3Q", nama: "PEJATEN KRAMATWATU" },
{ kode: "TIXP", nama: "JULANG CIKANDE" },
{ kode: "TGPJ", nama: "RAYA SAMPAY CILELES" },
{ kode: "TSS6", nama: "TAMAN PESONA SERANG" },
{ kode: "FVSU", nama: "RAYA PANIMBANG SUMUR " },
{ kode: "F0B8", nama: "BHAYANGKARA" },
{ kode: "FAGD", nama: "CIKANDE GRIYA ASRI" },
{ kode: "TT9A", nama: "SPBU PETIR" },
{ kode: "TFM1", nama: "KASERANGAN" },
{ kode: "FDGS", nama: "RAYA ANYER KM 17" },
{ kode: "T8SF", nama: "RAYA KURANJI SERANG" },
{ kode: "F776", nama: "BOJONEGORO 2" },
{ kode: "F85A", nama: "GRIYA LOPANG" },
{ kode: "TGC4", nama: "TAMBAK PAMARAYAN KM 7" },
{ kode: "FTE5", nama: "GARUDA MUNCANG" },
{ kode: "F117", nama: "WARINGIN KURUNG" },
{ kode: "F1X9", nama: "INDUSTRI MODERN CIKANDE" },
{ kode: "F2XT", nama: "SPBU LONTAR" },
{ kode: "F3FB", nama: "RAYA ANYER KM. 128" },
{ kode: "F59A", nama: "TAMAN BANTEN LESTARI" },
{ kode: "FIDS", nama: "CIUYAH" },
{ kode: "FMLX", nama: "BUMI NAGARA LESTARI" },
{ kode: "FO2Y", nama: "BANTEN INDAH PERMAI" },
{ kode: "FQ4X", nama: "PERUM BANJARSARI" },
{ kode: "FQ4Z", nama: "CIUJUNG INDAH RESIDENCE" },
{ kode: "FQJR", nama: "LEUWILIMUS CIKANDE" },
{ kode: "FT07", nama: "PULORIDA MERAK 2" },
{ kode: "FVLJ", nama: "REST AREA KM 68 B" },
{ kode: "FVM5", nama: "MUTIARA INDAH SERANG" },
{ kode: "FYG3", nama: "KADOMAS PANDEGLANG" },
{ kode: "T2AF", nama: "RAYA BINUANGEUN WANASALAM" },
{ kode: "T2YR", nama: "TRIP JAMAK SARI" },
{ kode: "T42Q", nama: "SAMANG RAYA" },
{ kode: "T50E", nama: "TAKTAKAN" },
{ kode: "T7LY", nama: "RAYA PALKA KM 28" },
{ kode: "T7X8", nama: "KYAI HAJI SOKHARI 50" },
{ kode: "T8GD", nama: "CIOMAS TEMBONG" },
{ kode: "T92P", nama: "RUKO BKP" },
{ kode: "T9N2", nama: "BANTEN LAMA" },
{ kode: "TDJO", nama: "SYECH NAWAWI 3" },
{ kode: "TFZ9", nama: "SELIKUR SUKA MAJU" },
{ kode: "TG2T", nama: "TAMAN MUTIARA INDAH 2" },
{ kode: "THAQ", nama: "KELAPA DUA SERANG" },
{ kode: "TIM4", nama: "SEPANG MOUNTAIN" },
{ kode: "TJFT", nama: "PALKA KM. 7" },
{ kode: "TLM1", nama: "RAYA SAMAUN BAKRI" },
{ kode: "TPMG", nama: "CURUG PANJANG LEBAK" },
{ kode: "TQG0", nama: "CILEGON KM 6" },
{ kode: "TR2M", nama: "ANYER 5" },
{ kode: "TRS1", nama: "RAYA SERANG-JKT KM 68 NO 7" },
{ kode: "TSLC", nama: "SUJUNG TIRTAYASA" },
{ kode: "TTBQ", nama: "PALM HILLS" },
{ kode: "TTSM", nama: "A YANI 152 SERANG" },
{ kode: "TUO3", nama: "TAMAN PURI INDAH SERANG" },
{ kode: "TXZO", nama: "SYECH NAWAWI" },
{ kode: "F58A", nama: "CITANGKIL" },
{ kode: "TO7W", nama: "JAWILAN" },
{ kode: "TLUQ", nama: "DI PANJAITAN" },
{ kode: "TM9S", nama: "KAMPUNG AMBON" },
{ kode: "F2R9", nama: "REST AREA KM 68 A" },
{ kode: "TEEC", nama: "BUKIT BAJA" },
{ kode: "F280", nama: "RSUD SERANG" },
{ kode: "T7B4", nama: "BANJARSARI" },
{ kode: "TEQ6", nama: "CIKANDE PERMAI" },
{ kode: "TINP", nama: "JOMBANG WETAN" },
{ kode: "TJCT", nama: "RAYA BANTEN KASEMEN" },
{ kode: "TLI2", nama: "SENEJA" },
{ kode: "TMS7", nama: "BUMI AGUNG" },
{ kode: "TQUC", nama: "BUMI MUTIARA SERANG" },
{ kode: "F5QY", nama: "RAYA MUNCANG SUKASARI" },
{ kode: "F83N", nama: "RUKO PURI CEMPAKA  SERANG" },
{ kode: "FFJW", nama: "METRO CILEGON" },
{ kode: "FXHI", nama: "SAYABULU" },
{ kode: "FXYS", nama: "TAMAN CILEGON INDAH" },
{ kode: "T14E", nama: "TB ISMAIL" },
{ kode: "T229", nama: "TAMBAK MANDAUNG" },
{ kode: "T4FD", nama: "CIKANDE PERMAI A1" },
{ kode: "T51E", nama: "SUMAMPIR" },
{ kode: "TBS8", nama: "RAYA SENTUL KRAGILAN" },
{ kode: "TDDD", nama: "PRIYAYI SERANG" },
{ kode: "TEMB", nama: "RAYA TAKTAKAN" },
{ kode: "TJCK", nama: "RAYA MANDALAWANGI KM 10" },
{ kode: "TO6F", nama: "GRAHA CISAIT" },
{ kode: "TS8O", nama: "TAMBAK BAYA LEBAK" },
{ kode: "TU7D", nama: "MANDALAWANGI" },
{ kode: "TVR9", nama: "RAYA MERAK KM. 1.5" },
{ kode: "TXF2", nama: "KOTASARI CILEGON" },
{ kode: "TYEJ", nama: "GEREM 3" },
{ kode: "TYWC", nama: "PANGERAN JAYAKARTA" },
{ kode: "TZ0N", nama: "BUMI PANDEGLANG INDAH" },
{ kode: "TPZ3", nama: "REGO PETIR" },
{ kode: "TCI8", nama: "IR DJUANDA RANGSBITUNG" },
{ kode: "F33R", nama: "RAYA LABUAN CARITA" },
{ kode: "FL3K", nama: "A M ROZI TAMAN JAYA" },
{ kode: "TOX0", nama: "RAYA KELAPA DUA SERANG" },
{ kode: "TP74", nama: "BUMI CIRUAS PERMAI" },
{ kode: "T0L7", nama: "RAYA MERAK" },
{ kode: "F32F", nama: "LABUAN II" },
{ kode: "TWDW", nama: "FRESH TB SUWANDI SERANG" },
{ kode: "T5PW", nama: "SEKONG CILEGON" },
{ kode: "FO35", nama: "CIBALIUNG" },
{ kode: "F8HI", nama: "RAYA MANDALAWANGI BENGKUNG" },
{ kode: "F1RF", nama: "GRAND SUTERA CILEGON" },
{ kode: "TP8A", nama: "PANIMBANG JAYA" },
{ kode: "T9Q2", nama: "RAYA CIRUAS" },
{ kode: "TP49", nama: "YOS SUDARSO MERAK" },
{ kode: "TQI5", nama: "MENGGER" },
{ kode: "T9F5", nama: "GARDU TANJAK" },
{ kode: "F39A", nama: "SERANG BARU" },
{ kode: "TS0X", nama: "TAMAN BARU CITANGKIL" },
{ kode: "T2I9", nama: "FRESH CIBEBER CILEGON" },
{ kode: "TQH8", nama: "SENOPATI CIKANDE" },
{ kode: "F17B", nama: "GUNUNG BATU RAYA" },
{ kode: "FZY5", nama: "FUTSAL 35" },
{ kode: "FR90", nama: "PULO AMPEL" },
{ kode: "T0CF", nama: "RAYA CIPOCOK PETIR KM 3.5" },
{ kode: "T7OD", nama: "CHRYSANT RESIDENCE" },
{ kode: "TFS4", nama: "FRESH CICERI SERANG" },
{ kode: "TV6G", nama: "GRIYA SERDANG INDAH" },
{ kode: "F3TF", nama: "SUNAN AMPEL WARNASARI" },
{ kode: "F8MM", nama: "LINTAS TIMUR SAMABOA" },
{ kode: "FDCT", nama: "KIAJURUM NO.5" },
{ kode: "FQNX", nama: "BRIGHT BY INDOMARET SPBU KADUSULUH" },
{ kode: "FTHF", nama: "SALIRA INDAH" },
{ kode: "T04M", nama: "TAMAN PURI INDAH 17 SERANG" },
{ kode: "T05E", nama: "FRESH TITAN ARUM" },
{ kode: "T1CE", nama: "PAKUPATAN II" },
{ kode: "T23T", nama: "RAWA ARUM" },
{ kode: "T2SM", nama: "MENES PANDEGLANG" },
{ kode: "T5KJ", nama: "TAMBAK PAMARAYAN KM1" },
{ kode: "T5YT", nama: "KP PABUARAN CIKANDE" },
{ kode: "T65O", nama: "FRESH A YANI NO 47 SERANG" },
{ kode: "T6P8", nama: "PASIR HAUR MALINGPING" },
{ kode: "T6W3", nama: "LEGOK SERANG" },
{ kode: "T8ET", nama: "IMAM BONJOL CIBEBER" },
{ kode: "T9K4", nama: "CIRUAS PONTANG" },
{ kode: "TBHP", nama: "IR SUTAMI NO 50" },
{ kode: "TCUT", nama: "WARINGIN KURUNG 2" },
{ kode: "TD4N", nama: "CIRACAS SERANG" },
{ kode: "TFDQ", nama: "PONDOK CILEGON INDAH 2" },
{ kode: "TGS0", nama: "GUNUNG KARANG NO 5" },
{ kode: "THJC", nama: "BHYANGKARA CILEGON NO 23" },
{ kode: "TJ8B", nama: "DUKUH LEUWIDAMAR" },
{ kode: "TJNU", nama: "KEDINDING KIBIN 2" },
{ kode: "TK7B", nama: "TAKTAKAN PANGGUNG JATI" },
{ kode: "TKE3", nama: "KH AGUS SALIM KEBONSARI" },
{ kode: "TNDN", nama: "TEMU PUTIH" },
{ kode: "TOBD", nama: "TAMAN PIPITAN INDAH" },
{ kode: "TOCA", nama: "OTISTA RANGKAS BITUNG" },
{ kode: "TOSI", nama: "PAGEBANGAN RAYA" },
{ kode: "TPBY", nama: "RAYA ANYER" },
{ kode: "TPY6", nama: "GRIYA LESTARI CISAIT" },
{ kode: "TQYB", nama: "MAGELARAN RAYA" },
{ kode: "TVUC", nama: "LINTAS TIMUR PANDEGLANG" },
{ kode: "TVWV", nama: "PURI ANGGREK" },
{ kode: "TWWB", nama: "PABUARAN CILEGON" },
{ kode: "TX8D", nama: "RAYA PETIR KM 3" },
{ kode: "TXTL", nama: "BOJONEGARA PEGANTUNGAN" },
{ kode: "TY0W", nama: "DUKUH KAUNG" },
{ kode: "TY4V", nama: "WANAKARTA BOJONEGARA" },
{ kode: "TZKP", nama: "KERTAJAYA" },
{ kode: "TY7A", nama: "BINONG PAMARAYAN" },
{ kode: "T0QM", nama: "CIKANDE KOPER" },
{ kode: "F04F", nama: "CIJAKU" },
{ kode: "TE8V", nama: "SPBU LINGKAR SELATAN" },
{ kode: "FUN8", nama: "MAJA LEBAK 2" },
{ kode: "T2O1", nama: "BUNDERAN CICERI" },
{ kode: "TD04", nama: "KOMPLEK PENDIDIKAN RANGKAS" },
{ kode: "T3LX", nama: "M SADELI" },
{ kode: "T9V2", nama: "LINGKAR SELATAN KM 1" },
{ kode: "TI4J", nama: "POINT POS SERANG" },
{ kode: "TSAO", nama: "KARABOHONG" },
{ kode: "FTLM", nama: "METROPOLIS RESIDENCE" },
{ kode: "TVTS", nama: "BABAKAN LOR" },
{ kode: "TI4Y", nama: "PAGELARAN MALINGPING" },
{ kode: "TW23", nama: "BAYAH LEBAK" },
{ kode: "TZ1T", nama: "SPBU CIAGEL KIBIN" },
{ kode: "T0E7", nama: "RAYA CINANGKA" },
{ kode: "FY3D", nama: "GUNUNG KENCANA" },
{ kode: "F98Q", nama: "SUMUR " },
{ kode: "TKMQ", nama: "KADU AGUNG CILELES" },
{ kode: "TX8K", nama: "CIMINYAK LEBAK" },
{ kode: "T6X9", nama: "MUNCANG" },
{ kode: "T33O", nama: "SUKAHUJAN" },
{ kode: "TWK2", nama: "TANARA" },
{ kode: "TGWY", nama: "CIKEUSAL PANOSOGAN" },
{ kode: "FY9K", nama: "SUKARATU" },
{ kode: "F03F", nama: "PASIR KURAY" },
{ kode: "T15D", nama: "BALONG RANGKAS" },
{ kode: "T0K8", nama: "CITASUK PADARINCANG" },
{ kode: "T0LJ", nama: "BAYAH BARAT" },
{ kode: "FEWW", nama: "SAKETI" },
{ kode: "T778", nama: "PANDEGLANG INDAH" },
{ kode: "THVP", nama: "MODERN CIKANDE" },
{ kode: "TIM1", nama: "RAYA MALINGPING  KM 4" },
{ kode: "FHVG", nama: "TB ISMAIL CILEGON" },
{ kode: "TNS1", nama: "CIKAREO LEBAK" },
{ kode: "TQE8", nama: "KADU BITUNG LEBAK" },
{ kode: "T567", nama: "RAYA LEUWIDAMAR KM 20" },
{ kode: "TP2C", nama: "CIWANDAN" },
{ kode: "TPSL", nama: "GUNUNG BARAT" },
{ kode: "TATD", nama: "RAYA SERANG GORDA" },
{ kode: "TGLC", nama: "KRAGILAN" },
{ kode: "T25T", nama: "CIOMAS SERANG" },
{ kode: "T64C", nama: "RAYA ANYER KM 1" },
{ kode: "T9ZR", nama: "FRESH PERUM BMW SERANG" },
{ kode: "TRRH", nama: "FRESH RAYA SERDANG KRAMATWATU" },
{ kode: "F6TD", nama: "PASAR JIPUT" },
{ kode: "F940", nama: "SULTAN AGENG TIRTAYASA" },
{ kode: "FHTZ", nama: "CIBUAH" },
{ kode: "FIUK", nama: "KADU AGUNG" },
{ kode: "T13J", nama: "MAJA GORDA" },
{ kode: "T1E7", nama: "PUSRI BANJARSARI" },
{ kode: "T5UM", nama: "CIMARGA" },
{ kode: "T5VC", nama: "JENDRAL SUDIRMAN 2" },
{ kode: "T8JM", nama: "RAYA CIRUAS PETIR KM 4" },
{ kode: "TCZ7", nama: "JL RAYA CIWARU SERANG" },
{ kode: "TMMS", nama: "SERANG CITY" },
{ kode: "TNEW", nama: "CIPOCOK " },
{ kode: "TRW8", nama: "RAYA BINUANGEUN KM 4" },
{ kode: "TS87", nama: "MAJASARI PANDEGLANG" },
{ kode: "TSTH", nama: "PERSADA BANTEN 2" },
{ kode: "TT0A", nama: "BAYAH 2" },
{ kode: "TUFN", nama: "SPBU CIPACUNG" },
{ kode: "TVW5", nama: "PASAURAN" },
{ kode: "TVXD", nama: "ALAM LESTARI SERANG" },
{ kode: "TWI3", nama: "RAYA BOJONEGARA KM 7" },
{ kode: "TW3R", nama: "PERTIGAAN SAMPAI" },
{ kode: "TVQT", nama: "RAYA SELIKUR KM 7.5" },
{ kode: "T8WF", nama: "SOGE PANIMBANG" },
{ kode: "FDYO", nama: "MUNJUL" },
{ kode: "FYEJ", nama: "SIMPANG MALINGPING" },
{ kode: "T1I9", nama: "WARUNG JAUD II" },
{ kode: "T2EC", nama: "LABUAN 5" },
{ kode: "T3YO", nama: "BANTEN KASUNYATAN" },
{ kode: "T7Y0", nama: "BOJONG PANDEGLANG" },
{ kode: "T9DK", nama: "TOL SERANG BARAT" },
{ kode: "THPS", nama: "RAYA MUNJUL KM 1" },
{ kode: "TJZ5", nama: "RAYA MERAK TEGALWANGI" },
{ kode: "TXJ3", nama: "WARUNG GUNUNG 2" },
{ kode: "TZJM", nama: "PAMARAYAN" },
{ kode: "T5CW", nama: "PELABUHAN MERAK" },
{ kode: "T9GR", nama: "PAKUPATAN" },
{ kode: "TGXH", nama: "CITEUREP RAYA" },
{ kode: "TPQT", nama: "CIASEM PANDEGLANG" },
{ kode: "T2ZV", nama: "CARITA 2" },
{ kode: "TEFP", nama: "BALONG CENTRAL" },
{ kode: "T4EB", nama: "PERTIGAAN CISEUKEUT" },
{ kode: "TU6P", nama: "NAMENG" },
{ kode: "FSE6", nama: "PURI DELTA" },
{ kode: "FX7U", nama: "MAJA SARUNI" },
{ kode: "T0H9", nama: "KAMPUNG AWEH" },
{ kode: "TY40", nama: "BANJAR IRIGASI" },
{ kode: "TD6I", nama: "BAMA PANDEGLANG" },
{ kode: "TA0U", nama: "PETIR KM 7" },
{ kode: "TCTD", nama: "PAHLAWAN RANGKAS" },
{ kode: "FZZV", nama: "CIKOTOK" },
{ kode: "TBXX", nama: "MEKAR SARI ANYER" },
{ kode: "F0SE", nama: "RAYA PETIR BAROS KM 06" },
{ kode: "F5Y0", nama: "CITRA MAJA" },
{ kode: "TQOY", nama: "RAYA IMAM BONJOL" },
{ kode: "TOCJ", nama: "CADASARI 2" },
{ kode: "T23E", nama: "LEWIDAMAR" },
{ kode: "TZZK", nama: "RAYA ANYER CIPACUNG" },
{ kode: "F00E", nama: "KARANG ANTU" },
{ kode: "F0NX", nama: "BOJONG LELES CIBADAK" },
{ kode: "F1XC", nama: "RAYA MAJA" },
{ kode: "F33M", nama: "CIBADAK LEBAK" },
{ kode: "F4MA", nama: "RAYA BAYAH CIKOTOK KM 5" },
{ kode: "F57V", nama: "PASAR CITEREUP" },
{ kode: "F778", nama: "CARITA" },
{ kode: "F7BG", nama: "CIEKEK" },
{ kode: "FAL1", nama: "RAYA PIPITAN-SERANG" },
{ kode: "FAP5", nama: "PADASUKA" },
{ kode: "FCJ4", nama: "BUJAL CIPANAS" },
{ kode: "FFP0", nama: "PASAR SABUT SAKETI" },
{ kode: "FK3V", nama: "KADUBANEN" },
{ kode: "FLKZ", nama: "RAYA PALKA KM 1" },
{ kode: "FPAC", nama: "PEREMPATAN CIKEDAL" },
{ kode: "FUPC", nama: "PASIR ONA" },
{ kode: "T182", nama: "ABDUL LATIEF NO 62" },
{ kode: "T1DO", nama: "SPBU CIRACAS" },
{ kode: "T1XA", nama: "BAROS " },
{ kode: "T2BL", nama: "CIJORO LEBAK" },
{ kode: "T6KN", nama: "RAYA CIKANDE KM 37" },
{ kode: "T8BS", nama: "SUNAN KALIJAGA 276" },
{ kode: "T8UT", nama: "MALINGPING III" },
{ kode: "TAID", nama: "MARGAGIRI BOJONEGARA" },
{ kode: "TB8A", nama: "TAMAN KRAKATAU" },
{ kode: "TCL6", nama: "RAYA JAYADININGRAT SERANG" },
{ kode: "TCRJ", nama: "TIRTAYASA PONTANG 2" },
{ kode: "TDP2", nama: "RAYA PADARINCANG" },
{ kode: "TF5W", nama: "CARITA" },
{ kode: "TFAI", nama: "SIMPANG TIGA CIBOLEGER" },
{ kode: "TFB2", nama: "PULORIDA LEBAK GEDE" },
{ kode: "TFHX", nama: "RUKO TAMAN SARI" },
{ kode: "TFUH", nama: "CIKATOMAS LEBAK" },
{ kode: "TGRB", nama: "CIKEUSAL" },
{ kode: "THLV", nama: "WARUNG GUNUNG KM 5" },
{ kode: "THVC", nama: "RAYA CILEGON SERANG KM 3" },
{ kode: "TK27", nama: "CIHERANG PANDEGLANG" },
{ kode: "TN8S", nama: "KH AGUS SALIM " },
{ kode: "TRC5", nama: "RAYA MANCAK KM 1" },
{ kode: "TT51", nama: "CIKADUEN" },
{ kode: "TXV2", nama: "GAJRUG" },
{ kode: "TZ4V", nama: "RAYA KAGUNGAN " },
{ kode: "TZKS", nama: "PARIGI CIKANDE" },
{ kode: "TB3S", nama: " RAYA BAROS SERANG" }, 
{ kode: "T2TG", nama: " RAYA PALKA PABUARAN" }

];
